import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, {Component} from 'react'
import { NextResponse } from 'next/server'


const pushLogin = () => {

  console.log("hey");
  
}


const _header = () => {

  return (

    <header className="text-3xl font-bold underline ">

        <Button>Button I've Made</Button>;
        <br />
        heyhey

    </header>

  );

}

const _footer = () => {

  return (

    <footer className={styles.footer}>
      <a
        href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        target="_blank"
        rel="noopener noreferrer"
      >
        Powered by{' '}
        <span className={styles.logo}>
          <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </span>
      </a>
    </footer>
    
  );

}


const comment = () => {

  return (
    <div className={styles.grid}>
      <a href="https://nextjs.org/docs" className={styles.card}>
        <h2>Documentation &rarr;</h2>
        <p>Find in-depth information about Next.js features and API.</p>
      </a>

      <a href="https://nextjs.org/learn" className={styles.card}>
        <h2>Learn &rarr;</h2>
        <p>Learn about Next.js in an interactive course with quizzes!</p>
      </a>

      <a
        href="https://github.com/vercel/next.js/tree/canary/examples"
        className={styles.card}
      >
        <h2>Examples &rarr;</h2>
        <p>Discover and deploy boilerplate example Next.js projects.</p>
      </a>

      <a
        href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
        className={styles.card}
      >
        <h2>Deploy &rarr;</h2>
        <p>
          Instantly deploy your Next.js site to a public URL with Vercel.
        </p>
      </a>
    </div>

  );

}

export default function Home() {

  return (
    
    <div className={styles.container}>
      
      <Head>
      
        <title>Oil Dashboard</title>
        
        <meta name="Oil Dashboard Next.JS Web App" content="Generated by create next appThis is an oil dashboard for oil, petrol companies or reselling business." />
        
        <link rel="icon" href="/oil_logo.ico" />
      
      </Head>
 
      <main className={styles.main}>

        <iframe className={`${styles.iframe}`} src='https://my.spline.design/homepageoil-d166c1f151174d924a30fd3dede24efd/'></iframe>
        
        
        <div className={`${styles.handlers} w-72 h-72 align-middle bg-red grid-cols-1 grid-rows-2 flex-col gap-4`}>
        
          <div className={styles.separator}></div>
  
          <input label="l-username" className={`${styles.company} w-full h-12 rounded-md`} placeholder="Username"/>

          <input label="l-password" className={`${styles.company} w-full h-12 rounded-md`} placeholder="Password"/>
        
          <button className={`w-full h-12 rounded-md text-xl text-left px-3 ${styles.cselect}`} onClick={pushLogin()}> Select </button> 
        
        </div>

      </main>

    </div>
  
  )

}
