
"""

Name: Gustavo Hammerschmidt.

Part 1:

1)

	Programming language: Python.

	a)   Σ = {a,b,c,d,e,f,g,h,i,j,k,l,m,
	          n,o,p,q,r,s,t,u,v,w,x,y,z,
	          0,1,2,3,4,5,6,7,8,9}

	b)	 L = {'def','for','var','int','bin','len'}



2)

	Alphabet:  Σ = {0,1}    |    Word:  W = 011


	What is the value of |W|?   |W| = 3

	If W is a word of Σ*, is W.W also a word of Σ*?

		- Yes, Σ* contains every combination of the alphabet Σ.


	List every prefix, suffix and subword of w.

		- Prefixes: ε, 0, 01, 011.
		- Suffixes: ε, 1, 11, 011.
		- Subwords: ε, 0, 1, 01, 11, 011.





3) Given the languages:

	L1 = {w in {a, b}* | w has an odd number of a's}
	L2 = {w in {a, b}* | w has at least two a's}

	a) List every word of L1 and L2 of length 3.

		abb, bab, bba, aaa,  aab, aba, baa.

		L1: abb, bab, bba, aaa.
		L2: aab, aba, baa, aaa.

	b) Determine the language that results from the operations below.

		a) L1∪L2:

			L1∪L2 = {w in {a, b}* | w has an odd number of a's OR w has at least two a's}

		b) L1 – L2

			L1 - L2 = {w in {a, b}* | w has an odd number of a's AND w has at most one a}

"""
print(
"\nName: Gustavo Hammerschmidt.\n\n1)\n\n Part 1: \n\n",
"a)      Σ = {a,b,c,d,e,f,g,h,i,j,k,l,m,n,o,p,q,r,s,t,u,v,w,x,y,z,0,1,2,3,4,5,6,7,8,9}\n",
"b)	 L = {'def','for','var','int','bin','len'}\n\n2)\n",
"Value: |W| = 3. \n Is W.W contained? - Yes, Σ* contains every combination of the alphabet Σ.\n",
"List ...:     - Prefixes: ε, 0, 01, 011.\n		- Suffixes: ε, 1, 11, 011.\n		- Subwords: ε, 0, 1, 01, 11, 011.\n\n3)\n",
"a) abb, bab, bba, aaa,  aab, aba, baa.\n b)\n   a) 	L1(union)L2 = {w in {a, b}* | w has an odd number of a's OR w has at least two a's}\n",
"  b)   L1 - L2 = {w in {a, b}* | w has an odd number of a's AND w has at most one a}\n"
)


"""

Part 2:

Let Σ = {0, 1}; give examples of words generated by the following regular expressions.

	- (0+1)* 10 (0+1)*
		Examples: 10, 010, 0100, 1100, 1101, ...

    - (0+1)* (11+00) (0+1)*
		Examples: 11, 00, 011, 000, 0110, 0111, 111, 100, ...


Write regular expressions for your favourite programming language that specify:

	- Reserved words (e.g. if, while, etc.)

		Reserved = if | while | def | for | else

		Reserved_Words = Reserved

	- Integer and real numbers (e.g. 10, 148, 1.96, etc.)

		Digits = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9
		Signs = + | -
		Float = .
		Integers = Signs Digits Digits*
		Floats = Signs Digits Digits* Float Digits Digits*

		Integers_and_Floats = Integers | Floats

	- Identifiers (e.g. variable names)

		Reserved = if | while | def | for | else
		Letter = a|b|c|d|e|f|g|h|i|j|k|l|m|n|o|p|q|r|s|t|u|v|w|x|y|z
		Digits = 0|1|2|3|4|5|6|7|8|9

		Variables = ( Letter (Digits + Letter)* ) - Reserved

"""
print("\nPart 2: \n\n Question 1: \n a) Examples: 10, 010, 0100, 1100, 1101, ... \n b) Examples: 11, 00, 011, 000, 0110, 0111, 111, 100, ... ",
"\n\n Question 2: answered in the comment block above.")
